# -*- coding: utf-8 -*-
"""AMFI NAV Download pipeline 10Jun2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iYNvcR_CSEb_Prcuqts8NzYEZYuXhHfj
"""

# Code to download AMFI data
# Updated by Rahul - 10 Jun 2026

import requests
import datetime as dt
import time
import os

from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

# =====================================================
# CONFIG
# =====================================================

BASE_URL = "https://portal.amfiindia.com/DownloadNAVHistoryReport_Po.aspx"

START_DATE = dt.date(2026, 1, 1)
END_DATE = dt.date(2026, 5, 31)

DOWNLOAD_DIR = "amfi_data_2026"

CHUNK_DAYS = 89
SLEEP_SECONDS = 2

# =====================================================
# CREATE OUTPUT FOLDER
# =====================================================

os.makedirs(DOWNLOAD_DIR, exist_ok=True)

print("🚀 Script Started")
print(f"📅 Start Date : {START_DATE}")
print(f"📅 End Date   : {END_DATE}")

# =====================================================
# SESSION WITH RETRY
# =====================================================

def get_session():

    session = requests.Session()

    retries = Retry(
        total=3,
        backoff_factor=1,
        status_forcelist=[
            500,
            502,
            503,
            504
        ]
    )

    session.mount(
        "https://",
        HTTPAdapter(max_retries=retries)
    )

    session.headers.update({
        "User-Agent": "Mozilla/5.0"
    })

    return session


# =====================================================
# AMFI DATE FORMAT
# Example:
# 2026-01-01 -> 01-Jan-2026
# =====================================================

def format_date(date_obj):
    return date_obj.strftime("%d-%b-%Y")


# =====================================================
# GENERATE 89-DAY CHUNKS
# =====================================================

def generate_chunks(start_date, end_date):

    current = start_date

    while current <= end_date:

        chunk_end = min(
            current + dt.timedelta(days=CHUNK_DAYS - 1),
            end_date
        )

        yield current, chunk_end

        current = chunk_end + dt.timedelta(days=1)


# =====================================================
# DOWNLOAD
# =====================================================

session = get_session()

chunks = list(
    generate_chunks(
        START_DATE,
        END_DATE
    )
)

print(f"\n📦 Total Chunks: {len(chunks)}")

success = 0
failed = 0
skipped = 0

for index, (chunk_start, chunk_end) in enumerate(
    chunks,
    start=1
):

    print("\n" + "=" * 60)
    print(
        f"📥 Chunk {index}/{len(chunks)}"
    )
    print(
        f"Date Range: {chunk_start} → {chunk_end}"
    )

    file_name = os.path.join(
        DOWNLOAD_DIR,
        f"nav_{chunk_start}_{chunk_end}.txt"
    )

    # Resume Support
    if os.path.exists(file_name):

        print(
            f"⏭️  Skipped (already exists)"
        )

        skipped += 1
        continue

    params = {
        "frmdt": format_date(chunk_start),
        "todt": format_date(chunk_end)
    }

    try:

        response = session.get(
            BASE_URL,
            params=params,
            timeout=60
        )

        print(
            f"HTTP Status: {response.status_code}"
        )

        if (
            response.status_code == 200
            and len(response.text) > 100
        ):

            with open(
                file_name,
                "w",
                encoding="utf-8"
            ) as f:
                f.write(response.text)

            size_mb = round(
                len(response.text.encode("utf-8"))
                / (1024 * 1024),
                2
            )

            print(
                f"✅ Saved: {os.path.basename(file_name)}"
            )

            print(
                f"📊 Size : {size_mb} MB"
            )

            success += 1

        else:

            print(
                "⚠️ Empty response received"
            )

            failed += 1

        time.sleep(
            SLEEP_SECONDS
        )

    except Exception as e:

        print(
            f"❌ Failed: {e}"
        )

        failed += 1

# =====================================================
# SUMMARY
# =====================================================

print("\n" + "=" * 60)
print("🎉 DOWNLOAD COMPLETE")
print("=" * 60)

print(f"✅ Success : {success}")
print(f"⏭️ Skipped : {skipped}")
print(f"❌ Failed  : {failed}")

print("\n📂 Files Created:")

for f in sorted(os.listdir(DOWNLOAD_DIR)):
    print(f"   {f}")

"""
===========================================================================
AMFI TXT -> SQLITE + EXCEL CONVERTER

PURPOSE
-------
Reads AMFI NAV history TXT files and creates:

1. SQLite database (.db)
2. Excel workbook (.xlsx)

One TXT file produces:

    nav_2026-01-01_2026-03-30.txt
            ↓
    nav_2026-01-01_2026-03-30.db
    nav_2026-01-01_2026-03-30.xlsx

OUTPUT FOLDERS
--------------
amfi_data/
db_output/
excel_output/

AUTHOR
------
Updated Robust Version
===========================================================================
"""

import pandas as pd
import glob
import os
import sqlite3
import time

# ==========================================================
# CONFIG
# ==========================================================

TXT_FOLDER = "amfi_data_2026"
DB_FOLDER = "db_output_2026"
EXCEL_FOLDER = "excel_output_2026"

# Create output folders
os.makedirs(DB_FOLDER, exist_ok=True)
os.makedirs(EXCEL_FOLDER, exist_ok=True)

# ==========================================================
# PROCESS SINGLE FILE
# ==========================================================

def process_txt_file(file_path):

    start_time = time.time()

    print("\n" + "=" * 70)
    print(f"🚀 Processing: {os.path.basename(file_path)}")
    print("=" * 70)

    all_data = []

    total_lines = 0
    blank_lines = 0
    invalid_structure = 0
    invalid_scheme_code = 0
    invalid_nav_value = 0

    # ------------------------------------------------------
    # READ FILE
    # ------------------------------------------------------

    try:

        with open(
            file_path,
            "r",
            encoding="utf-8"
        ) as f:

            lines = f.readlines()

    except Exception as e:

        print(f"❌ Failed reading file: {e}")
        return

    total_lines = len(lines)

    print(f"📄 Total Lines Read : {total_lines:,}")

    # ------------------------------------------------------
    # PARSE AMFI DATA
    # ------------------------------------------------------

    for line in lines:

        if not line.strip():
            blank_lines += 1
            continue

        parts = line.strip().split(";")

        # AMFI should have 8 columns
        if len(parts) < 8:
            invalid_structure += 1
            continue

        scheme_code = parts[0].strip()
        nav_value = parts[4].strip()
        nav_date = parts[7].strip()

        # Skip category/header rows
        if not scheme_code.isdigit():
            invalid_scheme_code += 1
            continue

        try:

            nav_value = float(nav_value)

            all_data.append([
                str(scheme_code),
                nav_date,
                nav_value
            ])

        except Exception:

            invalid_nav_value += 1
            continue

    # ------------------------------------------------------
    # VALIDATION
    # ------------------------------------------------------

    if not all_data:

        print("❌ No valid NAV records found")
        return

    print(f"✅ Valid Records     : {len(all_data):,}")

    # ------------------------------------------------------
    # DATAFRAME
    # ------------------------------------------------------

    df = pd.DataFrame(
        all_data,
        columns=[
            "scheme_code",
            "nav_date",
            "nav_value"
        ]
    )

    raw_rows = len(df)

    # ------------------------------------------------------
    # DATE CONVERSION
    # AMFI:
    # 01-Jun-2026
    #
    # Stored:
    # 2026-06-01
    # ------------------------------------------------------

    df["nav_date"] = pd.to_datetime(
        df["nav_date"],
        format="%d-%b-%Y",
        errors="coerce"
    )

    invalid_dates = df["nav_date"].isna().sum()

    df = df.dropna(
        subset=["nav_date"]
    )

    df["nav_date"] = (
        df["nav_date"]
        .dt.strftime("%Y-%m-%d")
    )

    # ------------------------------------------------------
    # EXPLICIT TYPES
    # ------------------------------------------------------

    df["scheme_code"] = (
        df["scheme_code"]
        .astype(str)
    )

    df["nav_value"] = (
        df["nav_value"]
        .astype(float)
    )

    # ------------------------------------------------------
    # REMOVE DUPLICATES
    # ------------------------------------------------------

    before_dedup = len(df)

    df = df.drop_duplicates(
        subset=[
            "scheme_code",
            "nav_date"
        ]
    )

    duplicates_removed = (
        before_dedup - len(df)
    )

    # ------------------------------------------------------
    # SORT
    # ------------------------------------------------------

    df = df.sort_values(
        [
            "scheme_code",
            "nav_date"
        ]
    )

    final_rows = len(df)

    # ------------------------------------------------------
    # OUTPUT FILE NAMES
    # ------------------------------------------------------

    base_name = os.path.splitext(
        os.path.basename(file_path)
    )[0]

    db_path = os.path.join(
        DB_FOLDER,
        f"{base_name}.db"
    )

    excel_path = os.path.join(
        EXCEL_FOLDER,
        f"{base_name}.xlsx"
    )

    # ------------------------------------------------------
    # SQLITE EXPORT
    # ------------------------------------------------------

    try:

        conn = sqlite3.connect(db_path)

        df.to_sql(
            "mf_nav",
            conn,
            if_exists="replace",
            index=False
        )

        conn.execute("""
            CREATE INDEX IF NOT EXISTS
            idx_scheme_date
            ON mf_nav
            (
                scheme_code,
                nav_date
            )
        """)

        conn.commit()

        verify_rows = pd.read_sql(
            """
            SELECT COUNT(*) cnt
            FROM mf_nav
            """,
            conn
        ).iloc[0]["cnt"]

        conn.close()

    except Exception as e:

        print(f"❌ SQLite Export Failed: {e}")
        return

    # ------------------------------------------------------
    # EXCEL EXPORT
    # ------------------------------------------------------

    try:

        df.to_excel(
            excel_path,
            index=False
        )

    except Exception as e:

        print(f"❌ Excel Export Failed: {e}")
        return

    # ------------------------------------------------------
    # SUMMARY
    # ------------------------------------------------------

    elapsed = round(
        time.time() - start_time,
        2
    )

    print("\n📊 FILE SUMMARY")
    print("-" * 40)

    print(f"Raw Records          : {raw_rows:,}")
    print(f"Invalid Dates        : {invalid_dates:,}")
    print(f"Duplicates Removed   : {duplicates_removed:,}")
    print(f"Final Records        : {final_rows:,}")

    print("\n📋 PARSE STATISTICS")
    print("-" * 40)

    print(f"Blank Lines          : {blank_lines:,}")
    print(f"Bad Structure Rows   : {invalid_structure:,}")
    print(f"Bad Scheme Codes     : {invalid_scheme_code:,}")
    print(f"Bad NAV Values       : {invalid_nav_value:,}")

    print("\n💾 OUTPUT")
    print("-" * 40)

    print(f"SQLite DB            : {db_path}")
    print(f"SQLite Rows          : {verify_rows:,}")

    print(f"Excel File           : {excel_path}")

    print(
        f"\n⏱️ Processing Time   : "
        f"{elapsed} sec"
    )

# ==========================================================
# MAIN
# ==========================================================

def main():

    txt_files = sorted(
        glob.glob(
            os.path.join(
                TXT_FOLDER,
                "*.txt"
            )
        )
    )

    if not txt_files:

        print(
            f"❌ No TXT files found "
            f"in '{TXT_FOLDER}'"
        )

        return

    print(
        f"📂 Found "
        f"{len(txt_files):,} TXT files"
    )

    for file in txt_files:

        process_txt_file(file)

    print("\n" + "=" * 70)
    print("🎉 ALL FILES PROCESSED")
    print("=" * 70)

# ==========================================================
# ENTRY POINT
# ==========================================================

if __name__ == "__main__":
    main()

"""
===========================================================================
AMFI DATABASE CONSOLIDATOR

PURPOSE
-------
Merge multiple AMFI chunk databases into one consolidated database.

Example:

INPUT FOLDER
------------
db_output_2026/

    nav_2026-01-01_2026-03-30.db
    nav_2026-03-31_2026-05-28.db
    nav_2026-05-29_2026-05-31.db

OUTPUT FOLDER
-------------
consolidated_db/

    amfi.db

OUTPUT TABLE
------------
nav_history
===========================================================================

"""

import sqlite3
import pandas as pd
import glob
import os
import time

# ==========================================================
# CONFIG
# ==========================================================

INPUT_DB_FOLDER = "db_output_2026"

OUTPUT_DB_FOLDER = "consolidated_db"

OUTPUT_DB_NAME = "amfi.db"

# ==========================================================
# CREATE OUTPUT FOLDER
# ==========================================================

os.makedirs(
    OUTPUT_DB_FOLDER,
    exist_ok=True
)

OUTPUT_DB = os.path.join(
    OUTPUT_DB_FOLDER,
    OUTPUT_DB_NAME
)

# ==========================================================
# START TIMER
# ==========================================================

start_time = time.time()

print("=" * 70)
print("🚀 AMFI DATABASE CONSOLIDATION STARTED")
print("=" * 70)

print(f"📂 Input Folder  : {INPUT_DB_FOLDER}")
print(f"📁 Output Folder : {OUTPUT_DB_FOLDER}")

# ==========================================================
# FIND INPUT DATABASES
# ==========================================================

db_files = sorted(
    glob.glob(
        os.path.join(
            INPUT_DB_FOLDER,
            "*.db"
        )
    )
)

# Exclude output DB if output folder == input folder

db_files = [
    f
    for f in db_files
    if os.path.basename(f) != OUTPUT_DB_NAME
]

if not db_files:

    print(
        f"❌ No database files found in "
        f"'{INPUT_DB_FOLDER}'"
    )

    raise SystemExit()

print(
    f"📚 Databases Found: "
    f"{len(db_files):,}"
)

# ==========================================================
# READ DATABASES
# ==========================================================

all_dfs = []

total_source_rows = 0

for db_file in db_files:

    try:

        print("\n" + "-" * 60)

        print(
            f"📖 Reading "
            f"{os.path.basename(db_file)}"
        )

        conn = sqlite3.connect(
            db_file
        )

        df = pd.read_sql_query(
            """
            SELECT
                scheme_code,
                nav_date,
                nav_value
            FROM mf_nav
            """,
            conn
        )

        conn.close()

        rows = len(df)

        total_source_rows += rows

        print(
            f"📊 Rows Read: "
            f"{rows:,}"
        )

        all_dfs.append(df)

    except Exception as e:

        print(
            f"⚠️ Skipping "
            f"{os.path.basename(db_file)}"
        )

        print(f"Reason: {e}")

# ==========================================================
# VALIDATE
# ==========================================================

if not all_dfs:

    print("❌ No valid data found")

    raise SystemExit()

# ==========================================================
# MERGE
# ==========================================================

print("\n" + "=" * 70)
print("🔄 MERGING DATABASES")
print("=" * 70)

final_df = pd.concat(
    all_dfs,
    ignore_index=True
)

print(
    f"📊 Source Rows: "
    f"{len(final_df):,}"
)

# ==========================================================
# DATA TYPES
# ==========================================================

final_df["scheme_code"] = (
    final_df["scheme_code"]
    .astype(str)
)

final_df["nav_value"] = (
    final_df["nav_value"]
    .astype(float)
)

# ==========================================================
# REMOVE DUPLICATES
# ==========================================================

before_dedup = len(final_df)

final_df = final_df.drop_duplicates(
    subset=[
        "scheme_code",
        "nav_date"
    ]
)

duplicates_removed = (
    before_dedup
    - len(final_df)
)

print(
    f"🧹 Duplicates Removed: "
    f"{duplicates_removed:,}"
)

# ==========================================================
# SORT
# ==========================================================

final_df = final_df.sort_values(
    [
        "scheme_code",
        "nav_date"
    ]
)

final_rows = len(final_df)

print(
    f"📈 Final Rows: "
    f"{final_rows:,}"
)

# ==========================================================
# SAVE DATABASE
# ==========================================================

print("\n" + "=" * 70)
print("💾 SAVING DATABASE")
print("=" * 70)

conn = sqlite3.connect(
    OUTPUT_DB
)

final_df.to_sql(
    "nav_history",
    conn,
    if_exists="replace",
    index=False
)

conn.execute("""
CREATE INDEX IF NOT EXISTS
idx_scheme_date
ON nav_history (
    scheme_code,
    nav_date
)
""")

conn.commit()

verify_rows = pd.read_sql_query(
    """
    SELECT COUNT(*) cnt
    FROM nav_history
    """,
    conn
).iloc[0]["cnt"]

conn.close()

# ==========================================================
# SUMMARY
# ==========================================================

elapsed = round(
    time.time() - start_time,
    2
)

print("\n" + "=" * 70)
print("🎉 CONSOLIDATION COMPLETE")
print("=" * 70)

print(
    f"📚 Source Databases : "
    f"{len(db_files):,}"
)

print(
    f"📊 Source Rows      : "
    f"{total_source_rows:,}"
)

print(
    f"🧹 Duplicates       : "
    f"{duplicates_removed:,}"
)

print(
    f"📈 Final Rows       : "
    f"{final_rows:,}"
)

print(
    f"🗄️ Verified Rows    : "
    f"{verify_rows:,}"
)

print(
    f"💾 Output Database  : "
    f"{OUTPUT_DB}"
)

print(
    f"⏱️ Runtime          : "
    f"{elapsed} sec"
)

print("=" * 70)

"""
=========================================================
AMFI DATABASE INSPECTOR
=========================================================

Purpose:
---------
1. Verify database exists
2. List all tables
3. Show nav_history schema
4. Show row count
5. Show first 10 rows
6. Show latest 10 rows
7. Show database size

=========================================================
"""

import sqlite3
import pandas as pd
import os

# =========================================================
# CONFIG
# =========================================================

DB_PATH = "consolidated_db/amfi.db"

# =========================================================
# VALIDATE FILE
# =========================================================

if not os.path.exists(DB_PATH):

    print(f"❌ Database not found: {DB_PATH}")
    raise SystemExit()

db_size_mb = round(
    os.path.getsize(DB_PATH) / (1024 * 1024),
    2
)

print("=" * 70)
print("🗄️ AMFI DATABASE INSPECTOR")
print("=" * 70)

print(f"📂 Database : {DB_PATH}")
print(f"💾 Size     : {db_size_mb} MB")

# =========================================================
# CONNECT
# =========================================================

conn = sqlite3.connect(DB_PATH)

# =========================================================
# SHOW TABLES
# =========================================================

print("\n" + "=" * 70)
print("📋 TABLES")
print("=" * 70)

tables = pd.read_sql_query(
    """
    SELECT name
    FROM sqlite_master
    WHERE type='table'
    ORDER BY name
    """,
    conn
)

print(tables)

# =========================================================
# SCHEMA
# =========================================================

print("\n" + "=" * 70)
print("🏗️ SCHEMA : nav_history")
print("=" * 70)

schema = pd.read_sql_query(
    """
    PRAGMA table_info(nav_history)
    """,
    conn
)

print(schema)

# =========================================================
# ROW COUNT
# =========================================================

print("\n" + "=" * 70)
print("📊 ROW COUNT")
print("=" * 70)

row_count = pd.read_sql_query(
    """
    SELECT COUNT(*) AS total_rows
    FROM nav_history
    """,
    conn
)

print(row_count)

# =========================================================
# FIRST 10 ROWS
# =========================================================

print("\n" + "=" * 70)
print("🔍 FIRST 10 ROWS")
print("=" * 70)

first_rows = pd.read_sql_query(
    """
    SELECT *
    FROM nav_history
    LIMIT 10
    """,
    conn
)

print(first_rows)

# =========================================================
# LAST 10 ROWS
# =========================================================

print("\n" + "=" * 70)
print("🔍 LAST 10 ROWS")
print("=" * 70)

last_rows = pd.read_sql_query(
    """
    SELECT *
    FROM nav_history
    ORDER BY nav_date DESC,
             scheme_code DESC
    LIMIT 10
    """,
    conn
)

print(last_rows)

# =========================================================
# DISTINCT SCHEMES
# =========================================================

print("\n" + "=" * 70)
print("📈 SCHEME SUMMARY")
print("=" * 70)

scheme_count = pd.read_sql_query(
    """
    SELECT COUNT(DISTINCT scheme_code)
    AS total_schemes
    FROM nav_history
    """,
    conn
)

print(scheme_count)

# =========================================================
# DATE RANGE
# =========================================================

print("\n" + "=" * 70)
print("📅 DATE RANGE")
print("=" * 70)

date_range = pd.read_sql_query(
    """
    SELECT
        MIN(nav_date) AS earliest_date,
        MAX(nav_date) AS latest_date
    FROM nav_history
    """,
    conn
)

print(date_range)

# =========================================================
# CLOSE
# =========================================================

conn.close()

print("\n" + "=" * 70)
print("✅ INSPECTION COMPLETE")
print("=" * 70)